repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff von.
    rev: v0.13.2
    hooks:
      # Run the formatter.
      - id: ruff-format
      # Run the linter.
      - id: ruff-check
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.8.22
    hooks:
      - id: uv-lock
      - id: uv-export
        args: ["--no-dev", "--output-file=requirements.txt", "--quiet"]
