openapi: 3.0.0
info:
  version: 0.0.0
  title: Nordic Microalgae
  description: API for Nordic Microalgae. __Under development__.
servers:
- url: /api/
  description: Development & Testing purposes
tags:
- name: taxa
  description: Lists and taxonomical information
- name: facts
  description: Collections of facts, traits and various description of taxa
- name: media
  description: Information about contributed media (e.g. pictures)
- name: articles
  description: Generic content such as pages, news, etc
paths:
  /taxa/:
    get:
      tags:
      - taxa
      description: Returns a list of taxa
      responses:
        200:
          description: Successful operation
          headers:
            X-Total:
              schema:
                type: integer
              description: Total number of taxa returned for the query
          content:
            application/json:
              schema:
                type: object
                properties:
                  taxa:
                    type: array
                    items:
                      $ref: '#/components/schemas/Taxon'
      parameters:
      - $ref: '#/components/parameters/taxon-list-fields'
      - $ref: '#/components/parameters/offset'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/name'
      - $ref: '#/components/parameters/rank'
      - $ref: '#/components/parameters/group'
      - $ref: '#/components/parameters/helcom-peg-only'
      - $ref: '#/components/parameters/illustrated-only'
      - $ref: '#/components/parameters/not-illustrated-only'
  /taxa/{slug}/:
    get:
      tags:
      - taxa
      description: Returns a single taxon
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Taxon'
        404:
          description: Taxon not found
      parameters:
      - $ref: '#/components/parameters/slug'
      - $ref: '#/components/parameters/taxon-fields'
  /facts/{slug}/:
    get:
      tags:
      - facts
      description: Returns facts about a single taxon
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Facts'
        404:
          description: Facts not found
      parameters:
      - $ref: '#/components/parameters/slug'
  /media/:
    get:
      tags:
      - media
      description: Returns a list of media
      responses:
        200:
          description: Successful operation
          headers:
            X-Total:
              schema:
                type: integer
              description: Total number of media returned for the query
          content:
            application/json:
              schema:
                type: object
                properties:
                  media:
                    type: array
                    items:
                      $ref: '#/components/schemas/Media'
      parameters:
      - $ref: '#/components/parameters/offset'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/media-type'
      - $ref: '#/components/parameters/media-fields'
      - $ref: '#/components/parameters/media-artist'
      - $ref: '#/components/parameters/media-gallery'
      - $ref: '#/components/parameters/media-taxon'
  /media/artists/:
    get:
      tags:
      - media
      description: Returns a list of photographers/artists along with their statistics for number of media.
      responses:
        200:
          description: Successful operation
          headers:
            X-Total:
              schema:
                type: integer
              description: Total number of photographers/artists returned for the query
          content:
            application/json:
              schema:
                type: object
                properties:
                  artists:
                    type: array
                    items:
                      type: object
                      properties:
                        artist:
                          type: string
                          example: Marie Johansen
                        number_of_contributions:
                          type: int
                          example: 200
  /media/tags/{tagset}/:
    get:
      tags:
      - media
      description: Returns a list of tags
      responses:
        200:
          description: Successful operation
          headers:
            X-Total:
              schema:
                type: integer
              description: Total number of tags for given tagset
          content:
            application/json:
              schema:
                type: object
                properties:
                  tags:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          example: HELCOM-PEG
      parameters:
      - $ref: '#/components/parameters/media-tagset'
  /articles/:
    get:
      tags:
      - articles
      description: Returns a list of articles
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  articles:
                    type: array
                    items:
                      $ref: '#/components/schemas/Article/properties/id'
      parameters:
      - $ref: '#/components/parameters/article-type'
      - $ref: '#/components/parameters/article-limit'
  /articles/{id}/:
    get:
      tags:
      - articles
      description: Returns a single article
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
        404:
          description: Article not found
      parameters:
      - $ref: '#/components/parameters/article-id'
components:
  parameters:
    slug:
      name: slug
      in: path
      description: Slug for the taxon
      required: true
      schema:
        type: string
        example: dinophysis-arctica
    offset:
      name: offset
      in: query
      description: Number of records to skip for pagination
      schema:
        type: integer
        format: int32
        minimum: 0
        default: 0
    limit:
      name: limit
      in: query
      description: Maximum number of records to return
      schema:
        type: integer
        format: int32
        minimum: 0
        maximum: 50
        default: 50
    name:
      name: name
      in: query
      description: Scientific name
      schema:
        type: string
        example: Dinophysis arctica
    rank:
      name: rank
      in: query
      description: Limit the list to taxa within a certain taxonomical rank
      schema:
        type: string
        example: Genus
        enum:
        - Class
        - Family
        - Form
        - Forma
        - Genus
        - Infraclass
        - Infrakingdom
        - Infraorder
        - Infraphylum
        - Kingdom
        - Order
        - Phylum
        - Phylum (Division)
        - Species
        - Subclass
        - Subfamily
        - Subgenus
        - Subkingdom
        - Suborder
        - Subphylum
        - Subphylum (Subdivision)
        - Subspecies
        - Subterclass
        - Superclass
        - Superfamily
        - Superorder
        - Tribe
        - Variety
    group:
      name: group
      in: query
      description: Limit the list to species that belongs to a certain group
      required: false
      schema:
        type: string
        example: diatoms
        enum:
        - all
        - ciliates
        - cyanobacteria
        - diatoms
        - dinoflagellates
        - other microalgae
        - other protozoa
    helcom-peg-only:
      name: helcom-peg-only
      in: query
      description: Limit the list to species found in the HELCOM-PEG list
      required: false
      schema:
        type: boolean
    illustrated-only:
      name: illustrated-only
      in: query
      description: Limit the list to illustrated species only
      required: false
      schema:
        type: boolean
    not-illustrated-only:
      name: not-illustrated-only
      in: query
      description: Limit the list to species not illustrated only
      required: false
      schema:
        type: boolean
    article-id:
      name: id
      in: path
      description: Identifier for the article
      required: true
      schema:
        type: string
        example: contact-us
    article-type:
      name: type
      in: query
      description: Article type
      schema:
        type: string
        example: page
        enum:
        - news
        - page
        default: page
    article-limit:
      name: limit
      in: query
      description: Maximum number of articles to return
      schema:
        type: int
        example: 10
    media-tagset:
      name: tagset
      in: path
      description: Tagset
      required: true
      schema:
        type: string
        example: galleries
        enum:
        - contrast_enhancement
        - galleries
        - preservation
        - stain
        - technique
    media-type:
      name: type
      in: query
      description: Media type
      schema:
        type: string
        example: image
        enum:
        - all
        - image
        default: all
    media-fields:
      name: fields
      in: query
      explode: false
      description: Fields to include in the response
      schema:
        type: array
        items:
          type: string
          enum:
            - slug
            - file
            - type
            - created_at
            - updated_at
            - attributes
            - renditions
    media-artist:
      name: artist
      in: query
      description: Limit the list to media for a specific photographer/artist
      schema:
        type: string
        example: Maria Karlberg
    media-gallery:
      name: gallery
      in: query
      description: Limit the list to media within a specific gallery
      schema:
        type: string
        example: HELCOM-PEG
        enum:
        - HELCOM-PEG
        - Kuylenstierna
        - Skagerrak-Kattegat
        - Norwegian Sea
        - Marine Research Institute - Iceland
        - Freshwater
        - Swedish benthic freshwater diatoms
        - Diatom resting stages
        - Dinoflagellate cysts
        - Other resting stages
    media-taxon:
      name: taxon
      in: query
      description: Limit the list to media related to a specific taxon
      schema:
        type: string
        example: dinophysis-arctica
    taxon-fields:
      name: fields
      in: query
      explode: false
      description: Fields to include in the response
      schema:
        type: array
        items:
          type: string
          enum:
            - slug
            - scientific_name
            - authority
            - rank
            - parent
            - classification
            - children
    taxon-list-fields:
      name: fields
      in: query
      explode: false
      description: Fields to include in the response
      schema:
        type: array
        items:
          type: string
          enum:
            - slug
            - scientific_name
            - authority
            - rank
            - parent
            - classification
            - children
            - image
  schemas:
    Facts:
      type: object
      properties:
        provider:
          type: string
          example: HELCOM-PEG
        collection:
          type: string
          example: Biovolumes
        attributes:
          type: object
    Media:
      type: object
      properties:
        slug:
          type: string
          example: dinophysis-arctica-1
        file:
          type: string
          example: dinophysis-arctica-1.jpg
        type:
          type: string
          example: image/jpeg
        created_at:
          type: string
          example: 2023-05-05T10:22:44:442Z
        updated_at:
          type: string
          example: 2023-05-05T12:10:16:312Z
        attributes:
          type: object
          properties:
            title:
              type: string
              example: Dinophysis arctica
            photographer_artist:
              type: string
              example: Bengt Karlson
            copyright_holder:
              type: string
              example: Bengt Karlson
            institute:
              type: string
              example: SMHI
            contributing_organisation:
              type: string
              example: SMHI
            contributor:
              type: string
              example: Bengt Karlson
            caption:
              type: string
              example: The text describing the illustration.
            sampling_date:
              type: string
              example: '2023-05-05'
            geographic_area:
              type: string
              example: Skagerrak - off shore
            location:
              type: string
              example: Where the water sample/organism was collected.
            latitude_degree:
              type: int
              example: 57
            latitude_minute:
              type: float
              example: 59.2
            longitude_degree:
              type: int
              example: 10
            longitude_minute:
              type: float
              example: 59.2
            license:
              type: string
              example: Creative Commons Attribution 3.0 Unported
            preservation:
              type: array
              items:
                type: string
                example: Lugols iodine
            stain:
              type: array
              items:
                type: string
                example: Calcofluor-Fluorescent brightener
            contrast_enhancement:
              type: array
              items:
                type: string
                example: DIC/Nomarski
            technique:
              type: array
              items:
                type: string
                example: Fluorescence microscopy
            galleries:
              type: array
              items:
                type: string
                example: HELCOM-PEG
        renditions:
          type: object
          properties:
            l:
              type: object
              properties:
                url:
                  type: string
                  example: '/media/l/dinophysis-arctica-1.jpg'
            m:
              type: object
              properties:
                url:
                  type: string
                  example: '/media/m/dinophysis-arctica-1.jpg'
            s:
              type: object
              properties:
                url:
                  type: string
                  example: '/media/s/dinophysis-arctica-1.jpg'
    Taxon:
      type: object
      properties:
        slug:
          type: string
          example: dinophysis-arctica
        scientific_name:
          type: string
          example: Dinophysis arctica
        authority:
          type: string
          example: Mereschkowsky, 1879
        rank:
          type: string
          example: Species
        parent:
          $ref: '#/components/schemas/RelatedTaxon'
        classification:
          type: array
          items:
            $ref: '#/components/schemas/RelatedTaxon'
        children:
          type: array
          items:
            $ref: '#/components/schemas/RelatedTaxon'
        image:
          type: object
          properties:
            l:
              type: object
              properties:
                url:
                  type: string
                  example: '/media/l/dinophysis-arctica-1.jpg'
            m:
              type: object
              properties:
                url:
                  type: string
                  example: '/media/m/dinophysis-arctica-1.jpg'
            s:
              type: object
              properties:
                url:
                  type: string
                  example: '/media/s/dinophysis-arctica-1.jpg'
    RelatedTaxon:
      type: object
      properties:
        slug:
          type: string
        scientific_name:
          type: string
        authority:
          type: string
        rank:
          type: string
    Article:
      type: object
      properties:
        id:
          type: string
          example: contact-us
        title:
          type: string
          example: Contact us
        content:
          type: string
          example: This is an __example__ of text content for an _article_.
