# Generated by Django 3.2.7 on 2021-11-18 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxa', '0002_synonym'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('taxon', models.OneToOneField(db_column='scientific_name', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='taxa.taxon')),
                ('data', models.JSONField(default=list)),
            ],
        ),
    ]
