# Generated by Django 3.2.7 on 2022-12-31 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=list)),
                ('taxon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taxa.taxon')),
            ],
        ),
    ]
