# Generated by Django 4.2.1 on 2023-05-26 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("taxa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facts",
            fields=[
                (
                    "taxon",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="taxa.taxon",
                    ),
                ),
                ("data", models.JSONField(default=list)),
            ],
            options={
                "db_table": "taxon_facts",
            },
        ),
    ]
