# Generated by Django 3.2.7 on 2021-11-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('scientific_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('parent_name', models.CharField(max_length=200)),
                ('authority', models.CharField(max_length=200)),
                ('rank', models.CharField(max_length=64)),
                ('classification', models.JSONField(default=list)),
                ('children', models.JSONField(default=list)),
                ('attributes', models.JSONField(default=dict)),
            ],
        ),
    ]
