# Generated by Django 4.2.27 on 2026-01-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0002_synonym'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLabelingTaxonDescription',
            fields=[
            ],
            options={
                'verbose_name': 'Labeling Guide Description',
                'verbose_name_plural': 'Labeling Guide Descriptions',
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('taxa.taxon',),
        ),
        migrations.AlterModelOptions(
            name='taxon',
            options={'ordering': ('scientific_name',), 'permissions': [('edit_image_labeling_description', 'Can edit image labeling description')]},
        ),
        migrations.AddField(
            model_name='taxon',
            name='image_labeling_description',
            field=models.TextField(blank=True, default='', help_text='Description text for the Image Labeling Guide page', verbose_name='Image Labeling Description'),
        ),
    ]
