# Generated by Django 5.2.10 on 2026-01-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxa", "0003_imagelabelingtaxondescription_alter_taxon_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrphanedDescription",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "old_taxon_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Orphaned Image Labeling Description",
                "verbose_name_plural": "Orphaned Image Labeling Descriptions",
                "db_table": "orphaned_description",
                "ordering": ["-updated_at"],
            },
        ),
    ]
