# Generated by Django 4.1.5 on 2023-05-05 07:18

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion
import media.models
import media.renditions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(editable=False)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('file', models.FileField(upload_to=media.models.primary_path_for_media)),
                ('type', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('renditions', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('taxon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxa.taxon')),
            ],
            bases=(models.Model, media.renditions.ModelActionsMixin),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('media.media',),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('taxon', 'priority'), name='unique_media_priority'),
        ),
    ]
