# Generated by Django 4.2.10 on 2024-03-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'permissions': [('manage_others', 'Can manage others media')]},
        ),
    ]
