# Generated by Django 4.2.27 on 2026-01-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_media_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLabelingImage',
            fields=[
            ],
            options={
                'verbose_name': 'Labeling Guide Image',
                'verbose_name_plural': 'Labeling Guide Images',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('media.image',),
        ),
    ]
