name: CI/CD

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src

      - name: Install Django app files
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/dist/app
          rsync -av \
              --exclude=.* \
              ${GITHUB_WORKSPACE}/src/ \
              ${GITHUB_WORKSPACE}/dist/app/

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Build wheel archives for dependencies
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/dist/wheels
          python -m pip install --upgrade pip
          python -m pip wheel -v \
            -r ${GITHUB_WORKSPACE}/src/requirements.txt \
            -w ${GITHUB_WORKSPACE}/dist/wheels
          cat ${GITHUB_WORKSPACE}/src/requirements.txt >> \
              ${GITHUB_WORKSPACE}/dist/requirements.txt

      - name: Install dependencies from wheel archives
        run: |
          python -m pip install -v --no-index \
            -f ${GITHUB_WORKSPACE}/dist/wheels \
            -r ${GITHUB_WORKSPACE}/dist/requirements.txt

      - name: Install Django static files
        run: |
          python ${GITHUB_WORKSPACE}/src/manage.py \
            collectstatic --no-input
          rsync -av \
            ${GITHUB_WORKSPACE}/static/ \
            ${GITHUB_WORKSPACE}/dist/static/

      - name: Archive Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: dist

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend
          path: ./backend

      - name: Create dist archive
        run: |
          tar -czvf \
            "nordicmicroalgae-backend-${{ github.ref_name }}-dist.tar.gz" \
            backend

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release create \
            "${{ github.ref_name }}" \
            "nordicmicroalgae-backend-${{ github.ref_name }}-dist.tar.gz" \
            --repo "${{ github.repository }}" \
            --notes ""

  staging:
    if: github.ref == 'refs/heads/next'
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
    secrets: inherit

  production:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
    secrets: inherit
